from __future__ import annotations
import os
from pathlib import Path
from elevenlabs import ElevenLabs
from .tts_backend import TTSBackend

class ElevenLabsTTS(TTSBackend):
    def __init__(self, api_key: str | None = None, model_id: str = "eleven_multilingual_v2"):
        self.client = ElevenLabs(api_key=api_key or os.environ["ELEVENLABS_API_KEY"])
        self.model_id = model_id

    def synthesize(self, text: str, voice_id: str, output: Path) -> Path:
        # TODO: Remember in the future for syncing purposes
        # This call might also need to ask for timestamped
        # info with text.
        # This is a bit of a conundrum because even though that information
        # Would be generated by elevenlabs, this is not a "ElevenLabsNarrate" concern, 
        # but a sync phase related concern. 
        # Will investigate later 
        # But to some extent narration and sync have to communicate
        # as syncing depends on narration details
        # For now(well, for the very near future), the workaround would be to use ResolvedEntry.extras 
        # So synthesize() emits the call, and timestamped info is put in ResolvedEntry.extras for the sync phase to
        # use later. That makes sense also because technically you could argue storing the timestamped info
        # is "resolution"
        audio = self.client.text_to_speech.convert(
            voice_id=voice_id, text=text, model_id=self.model_id,
        )
        with open(output, "wb") as f:
            for chunk in audio:
                f.write(chunk)
        return output
